name: Download & Transfor GSheet Content

on:
#   schedule:
#   - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - id: 'fetch_worksheet'
        uses: jroehl/gsheet.action@v1.0.0
        with:
          spreadsheetId: ${{ secrets.GSHEET_ID }}
          commands: |
            [ {"command": "getData", "args": { "range": "Master!B:V" } } ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: dump results
        env:
          RESULTS: ${{ steps.fetch_worksheet.outputs.results }}
        run: echo "$RESULTS" | jq '.results[0].result.rawData' > array_format.json
      - name: push changes
        uses: test-room-7/action-update-file@v1
        with:
          file-path: array_format.json
          commit-msg: Update resources
          github-token: ${{ secrets.GITHUB_TOKEN }}
